# Generated by Django 2.0.5 on 2018-05-24 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_id', models.CharField(max_length=10)),
                ('fixed_date', models.DateTimeField(verbose_name='date fixed')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=200)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mining_main.Bug')),
            ],
        ),
    ]
