# Generated by Django 2.0.5 on 2018-06-05 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='fixed_date',
        ),
        migrations.RemoveField(
            model_name='file',
            name='bug',
        ),
        migrations.AddField(
            model_name='bug',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='file',
            name='added',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='bugs',
            field=models.ManyToManyField(to='mining_main.Bug'),
        ),
        migrations.AddField(
            model_name='file',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
    ]
