# Generated by Django 2.0.6 on 2018-06-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_main', '0002_auto_20180605_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='involved',
            field=models.IntegerField(default=0),
        ),
    ]
