# Generated by Django 2.0.6 on 2018-06-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_main', '0003_file_involved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('files', models.ManyToManyField(to='mining_main.File')),
            ],
        ),
    ]
