# Generated by Django 2.0.6 on 2018-06-07 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_main', '0004_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='author_name',
        ),
        migrations.AddField(
            model_name='file',
            name='last_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='file',
            name='total_changeset',
            field=models.IntegerField(default=0),
        ),
    ]
