# Generated by Django 2.0.6 on 2018-06-09 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mining_main', '0006_auto_20180609_0618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='release',
        ),
    ]
