# Generated by Django 2.0.6 on 2018-06-09 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mining_main', '0007_remove_file_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='release',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mining_main.Release'),
            preserve_default=False,
        ),
    ]
