# Generated by Django 2.0.6 on 2018-06-12 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mining_main', '0008_file_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='file',
            name='last_updated',
        ),
    ]
